// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSHENQMp6tfHLRoVuZk-U7HrKxiDsjaQ',
    appId: '1:708212193698:web:6565c3d05ae266f994dafb',
    messagingSenderId: '708212193698',
    projectId: 'cucikan-v2',
    authDomain: 'cucikan-v2.firebaseapp.com',
    storageBucket: 'cucikan-v2.firebasestorage.app',
    measurementId: 'G-HYP38T0WGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFso3yx9TJwdUeImBjXaH1zbnX7e0jSzk',
    appId: '1:708212193698:android:0c003db505a1d28694dafb',
    messagingSenderId: '708212193698',
    projectId: 'cucikan-v2',
    storageBucket: 'cucikan-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6L8ig84-ZhqjxFNGQGapiXLZVPhwqND8',
    appId: '1:708212193698:ios:3774de72938b2f2b94dafb',
    messagingSenderId: '708212193698',
    projectId: 'cucikan-v2',
    storageBucket: 'cucikan-v2.firebasestorage.app',
    iosClientId: '708212193698-gl2a8mrcaj2m5l684e6ojnilmprr9i8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cucikanV2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6L8ig84-ZhqjxFNGQGapiXLZVPhwqND8',
    appId: '1:708212193698:ios:3774de72938b2f2b94dafb',
    messagingSenderId: '708212193698',
    projectId: 'cucikan-v2',
    storageBucket: 'cucikan-v2.firebasestorage.app',
    iosClientId: '708212193698-gl2a8mrcaj2m5l684e6ojnilmprr9i8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cucikanV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbSHENQMp6tfHLRoVuZk-U7HrKxiDsjaQ',
    appId: '1:708212193698:web:d803de76795db18994dafb',
    messagingSenderId: '708212193698',
    projectId: 'cucikan-v2',
    authDomain: 'cucikan-v2.firebaseapp.com',
    storageBucket: 'cucikan-v2.firebasestorage.app',
    measurementId: 'G-E9SLT4D69G',
  );
}
